### ISSUE TITLE
Update in library.player

### ISSUE THREAD

**Issue by Kasea** [hsdn/tera-guide-core#3]
The variable `playersInParty` has been updated in `Library.player`. See https://github.com/tera-toolbox-mods/library/commit/907319e8c65458ceeb868c919f7c6a41820efdb0

Fix is changing `playersInParty.includes(gameId)` to `playersInParty.has(gameId)`

Note: Needs to be fixed here as well https://github.com/hsdn/tera-guide/blob/d3d032fcb278fbdb5f7c4ee16d66be8b1eb16f06/guides/3020.js#L155

**Comment by Kasea** [comment]
Forgot to link this https://github.com/hsdn/tera-guide-core/blob/60ebd9eb75d05cf5f3ef7ad1787e83931ce42be4/lib/core/events/hooks/S_ABNORMALITY_BEGIN.js#L23

**Comment by justkeepquiet** [comment]
Hi, updated https://github.com/hsdn/tera-guide-core/commit/d8afecf9651276c47513bcb4de9b2f27855f3647. Thank you for notice.
