### ISSUE TITLE
Red Message Cascade - Menma

### ISSUE THREAD

**Issue by Reny900** [hsdn/tera-guide-core#4]
at a certain point today out of nowhere i noticed this messages, simple by alt tabbing, the game was functioning as normal, nothing really visible ingame

"[15:50:08.117] [dispatch] [tera-guide] handle: error running hook for S_ABNORMALITY_BEGIN<4>
hook: (anonymous) in tera-guide
data: {
  target: 72198331709810377n,
  source: 0n,
  id: 4610,
  duration: 3539352n,
  stacks: 1,
  hitCylinderId: 0,
  unk3: 2
}
error: player.playersInParty.has is not a function
    at Object.module.exports.callback (D:\Games\Menma's Tera\TeraToolbox Private\mods\tera-guide-core\lib\core\events\hooks\S_ABNORMALITY_BEGIN.js:45:35)
    at Object.callback (D:\Games\Menma's Tera\TeraToolbox Private\mods\tera-guide-core\lib\core\hooks.js:110:15)"
and displayed as red not sure what happened, didnt notice anything until i put the toolbox window on focus by mistake.

This is the error log
    
[12_marzo_2023.log](https://github.com/hsdn/tera-guide-core/files/10951260/12_marzo_2023.log)

**Comment by justkeepquiet** [comment]
You are using an outdated version of the **Library** module.
Install the latest version from here: https://github.com/tera-private-toolbox/library/archive/refs/heads/master.zip

**Comment by Reny900** [comment]
i'm wondering why it didnt auto-update, since it was enabled. Thanks for the input

**Comment by justkeepquiet** [comment]
Most likely you used the toolbox from valkyteq, the library is not updated there.
We recommend using this https://github.com/tera-private-toolbox/tera-toolbox
